---
title: "Emissions Dashboard"
subtitle: "Analyzing global CO₂ emissions trends from 1990 to 2022."
format:
  dashboard:
    orientation: rows
    theme: cosmo
execute:
  echo: false
---


```{python}
import pandas as pd
import numpy as np
import plotly.express as px
from itables import show
import country_converter as coco

# Load the data
emissions = pd.read_csv("data/co2_cons.csv")

# Initial Cleaning
emissions = emissions.rename(columns={"name": "country"})
# emissions.query("country == 'China'")[["country", "2020", "2021", "2022"]]

#for col in ["2021", "2022"]:
#    has_k = emissions[col].str.contains("k")
#    values = emissions[col].str.replace("k", "")
#    emissions[col] = np.where(has_k, values.astype(float) * 1000, values.astype(float))

#emissions.query("country == 'China'")[["country", "2020", "2021", "2022"]]

# Table Section
table_df = emissions[['country', '2000', '2022']]
table_df["Absolute Change"] = table_df['2022'] - table_df['2000']
table_df["Relative Change"] = (table_df["Absolute Change"] / table_df["2000"]) * 100
table_df["Relative Change"] = table_df["Relative Change"].round(0).astype(str) + "%"

# Chart Section
emissions_long = emissions.melt(
    id_vars=['country'],
    value_vars=[str(y) for y in range(1990, 2023)],
    var_name='year',
    value_name='emissions'
)

emissions_long["year"] = pd.to_numeric(emissions_long["year"])
emissions_long["emissions"] = pd.to_numeric(
    emissions_long["emissions"].astype(str).str.replace("−", "-")
)

emissions_long_1990_2022 = emissions_long[
    (emissions_long['year'] >= 1990) &
    (emissions_long['year'] <= 2022)
]

countries = ["China", "United States", "India", "Germany", "Brazil"]

emissions_long_subset = emissions_long[
    emissions_long['country'].isin(countries)
]

fig_chart = px.line(
    emissions_long_subset,
    x='year',
    y='emissions',
    color='country',
    title="CO₂ Emissions (1990–2022) for Selected Countries"
)

# Mapping Section
emissions_long_1990_2022["country_code"] = coco.convert(
    emissions_long_1990_2022["country"], to="ISO3"
)

fig_map = px.choropleth(
    emissions_long_1990_2022,
    locations="country_code",
    color="emissions",
    hover_name="country",
    animation_frame="year",
    title="Global CO2 Emissions (1990-2022)",
)
```

# HOME

## Row {height="30%"}

::: {.valuebox icon="globe" color="danger" title="Total CO₂ Emissions (2022)"}
`{python} f"{emissions['2022'].sum():,.0f}"`
:::


::: {.valuebox icon="activity" color="primary" title="Avg CO₂ Emissions per Country"}
`{python} f"{emissions['2022'].mean():,.2f}"`
:::

::: {.valuebox icon="map" color="success" title="Countries Reporting Emissions"}
`{python} f"{emissions['country'].nunique():,.0f}"`
:::

## ROW {height="70%"}



```{python}
show(table_df)
```

# CHART
**CO₂ Emissions Trends (1990–2022)**
Line chart showing the trend of CO₂ emissions over time for China, India, Germany and Brazil.

## ROW {height="70%"}


```{python}
fig_chart
```


# MAP

## Row

```{python}
fig_map
```


# ABOUT

This dashboard explores global consumption-based CO₂ emissions using data from Gapminder. It provides an overview of how emissions have changed over time across different countries.

The dashboard includes:

A **data table** comparing emissions between 2000 and 2022, including absolute and relative changes.

A **trend chart** showing how emissions evolved from 1990 to 2022 for selected countries.

An **interactive world map** displaying global emissions by country over time.

These visualizations help highlight regional patterns, major contributors to global emissions, and long-term trends in carbon output.


## DATA SOURCE

Data: Gapminder – CO₂ Total Emissions Dataset  
Source: [Gapminder Data Portal](https://www.gapminder.org/data/)

The dataset contains country-level consumption-based CO₂ emissions covering multiple decades. It includes emissions in metric tons for each country and year, allowing for analysis of trends and comparisons across nations.